### ISSUE TITLE
How to get the header/col datatype during parsing a CSV file

### ISSUE THREAD

**Issue by papyr** [paillave/Etl.Net#276]
in my case, the _source CSV data file_ and header content/types change often -- basically unknown, while parsing or before parsing I need to first Discover the Data Types of the data in the cols.

I just need to load & save the data into a Sql table based on whatever data & DataTypes there are in the CSV file. Can I auto load the CSV data and datatypes into the DB automatically with ETL box. I saw your expando example but was a little lost how to achieve a high level task

For e.g high level algorithm, how would I achieve this in your lib.
```
// Scan first 9 rows to discover the datatypes in the CSV file cols
var etlPrasedFile = ETL.Paillave.Open/parseCSV(someUnknownData.csv).ScanRows(9)
foreach (var col in etlPrasedFile )
new dataTable.addColumn(etlParsedFile.GetNextHeaderCol)
CreateNewSqlServerTable
LoadDatatoSqlTable??
```

thanks

**Comment by paillave** [comment]
ETL.NET csv parser doesn't provide any feature like this at the moment. But... you can implement your own operator/valueprovider if you feel the need. You can check the documentation for the new version.
