### ISSUE TITLE
[FtpFileValueProvider] NotImplementedException after execution

### ISSUE THREAD

**Issue by nicolasjolet** [paillave/Etl.Net#323]
Hi,

I'm using the library as shown in the samples:

```
contextStream.CrossApply("Get Files", new FtpFileValueProvider("SRC", "Solar exports", "files from ftp", connectionParams, providerParams))
        .Do("print files to console", i => Console.WriteLine(i.Name));
```
File names are printed correctly, but I'm always getting an **NotImplementedException** at the end of the execution.

It seems to be linked to the **FileValueProviderBase.TypeName** that explicitly throws a **NotImplementedException**.
The following change attempt has fixed the issue in my local copy:
```
namespace Paillave.Etl.Core
{
    public abstract class FileValueProviderBase<TConnectionParameters, TProviderParameters> : IFileValueProvider, IValuesProvider<object, IFileValue>
    {
   [...]

        public string TypeName => this.GetType().Name; // throw new NotImplementedException()
```

Am I using the ftp provider a wrong way or should it be fixed?

Thank you by advance,
Nicolas

**Comment by paillave** [comment]
Solved, use the version v2.0.21-beta (checking "pre release" in your nuget browser). Sorry for this terrible mistake. FYI this version uses NET6.
