### ISSUE TITLE
SimpleConsoleExecutionDisplay - documentation not inline with sources, any clues how to make it work ? :-)

### ISSUE THREAD

**Issue by nicolasjolet** [paillave/Etl.Net#328]
Hi,

I'm trying to use the `SimpleConsoleExecutionDisplay`.

The documentation use a parameterless constructor but the class has actually no default ctor.
Passing `default` leads to `NullReferenceException`. Passing `new()` for each params seems ok, but I don't know what is expected.

Moreover the doc specify to use the `Initialize()` method with a `structure` variable (of type `JobDefinitionStructure`), but I've no idea where to get that "structure" ?
I've passed the StreamProcessRunner.GetDefinitionStructure(), is it correct ?

Thank you by advance :)

**Comment by paillave** [comment]
Hello,
Indeed, there is a glich in this class. There should be a parameter less constructor. Thanks for pointing that out. I will solve it.
Your workaround will work with no problem. And indeed, you called `Initialize` the proper way.
I will improve the documentation.

**Comment by paillave** [comment]
corrections published

- `SimpleConsoleExecutionDisplay` has a parameterless constructor.
- The method `Initialize` can also receive a `IStreamProcessObserver` (`StreamProcessRunner<>` implements it) instead of `JobDefinitionStructure`
